name: Create Pages

on:
  workflow_run:
    workflows: ['Auto Release']
    branches: [main]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: divlook
          user_email: uihyeon.cha@gmail.com
          publish_dir: dist
